# Generated by Django 5.0.2 on 2024-04-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_branch_branch_name_alter_subject_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(default='ABC', max_length=15),
        ),
        migrations.AddField(
            model_name='question',
            name='question_mark',
            field=models.IntegerField(default=1),
        ),
    ]
